### ISSUE TITLE
Use it for the crack detection

### ISSUE THREAD

**Issue by g5996706** [TY-Shi/LIOT#3]
Thanks for this awesome project.
I want to do crack detection, but I think the examples are all for the drive database, how can I modify it to use it for the crack database and detection?

**Comment by TY-Shi** [comment]
Thank you for your attention and support！ Using LIOT to the crack dataset is very simple. The first way, You can use LIOT.py to transfer RGB crack to LIOT crack off-line! In more detail, You can change Img_dir and Save_dir to define which dataset you want to transfer and where to save it.  Also, remember to uncomment the following two lines to save the image.
"deal_filename = save_path[:-4] + ".tiff""
"tifffile.imsave(deal_filename,Deal_img)"
Second, we will also try to release a faster version to trans LIOT online for training more convenient in the coming months.
Hope we can help you！

**Comment by TY-Shi** [comment]
In the offline way, you can use these LIOT crack images to any existing method or pipeline!

**Comment by g5996706** [comment]
Thanks for your reply,I have transferred the data through LIOT.py.
But I don't know how to apply the LIOT data to the prepare_datasets.py.
I'm not sure what data should correspond to original_imgs_test and groundTruth_imgs_test and borderMasks_imgs_test

**Comment by TY-Shi** [comment]
The perpare_datasets.py is for DRIVE. Thus, for the CrackTree dataset, you can make some changes in this script. The ground truth test image corresponds to the  groundTruth_imgs_test and LIOT crack test images correspond to original_imgs_test. And crack doesn't need border masks_img_test. You can split the test and train the dataset as you want.  For training or testing, you can also your existing method to train and test LIOT images.

**Comment by TY-Shi** [comment]
So you also don't need prepare_datasets.py. If you train the crack detection in your way, you can load LIOT images and ground truth as RGB images before!

**Comment by g5996706** [comment]
Thanks for your reply,I will try it.
