### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by htx-rest** [TY-Shi/LIOT#4]
D:\Anaconda3\envs\pytorch-vessel\python.exe D:/LIOT-main/LIOT.py
D:/LIOT-main/LIOT.py:67: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "distance_weight_binary_pattern_faster" failed type inference due to: non-precise type pyobject
During: typing of argument at D:/LIOT-main/LIOT.py (73)

File "LIOT.py", line 73:
def distance_weight_binary_pattern_faster(img):
    <source elided>
	'''
    img = np.asarray(img)  # input image H*W*C
    ^

  @numba.jit()
D:/LIOT-main/LIOT.py:67: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "distance_weight_binary_pattern_faster" failed type inference due to: Cannot determine Numba type of <class 'numba.core.dispatcher.LiftedLoop'>

File "LIOT.py", line 81:
def distance_weight_binary_pattern_faster(img):
    <source elided>

    for direction in range(0, 4):
    ^

  @numba.jit()
D:\Anaconda3\envs\pytorch-vessel\lib\site-packages\numba\core\object_mode_passes.py:152: NumbaWarning: Function "distance_weight_binary_pattern_faster" was compiled in object mode without forceobj=True, but has lifted loops.

File "LIOT.py", line 73:
def distance_weight_binary_pattern_faster(img):
    <source elided>
	'''
    img = np.asarray(img)  # input image H*W*C
    ^

  state.func_ir.loc))
D:\Anaconda3\envs\pytorch-vessel\lib\site-packages\numba\core\object_mode_passes.py:162: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "LIOT.py", line 73:
def distance_weight_binary_pattern_faster(img):
    <source elided>
	'''
    img = np.asarray(img)  # input image H*W*C
    ^

  state.func_ir.loc))
D:/LIOT-main/LIOT.py:67: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "distance_weight_binary_pattern_faster" failed type inference due to: No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(array(int64, 2d, C), array(bool, 2d, C), Literal[int](1))
 
There are 16 candidate implementations:
   - Of which 14 did not match due to:
   Overload of function 'setitem': File: <numerous>: Line N/A.
     With argument(s): '(array(int64, 2d, C), array(bool, 2d, C), int64)':
    No match.
   - Of which 2 did not match due to:
   Overload in function 'SetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 176.
     With argument(s): '(array(int64, 2d, C), array(bool, 2d, C), int64)':
    Rejected as the implementation raised a specific error:
      NumbaTypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
  raised from D:\Anaconda3\envs\pytorch-vessel\lib\site-packages\numba\core\typing\arraydecl.py:73

During: typing of setitem at D:/LIOT-main/LIOT.py (97)

File "LIOT.py", line 97:
def distance_weight_binary_pattern_faster(img):
    <source elided>
            tmp_map = gray_img.astype(np.int64) - new_pad.astype(np.int64)
            tmp_map[tmp_map > 0] = 1
            ^

  @numba.jit()
D:\Anaconda3\envs\pytorch-vessel\lib\site-packages\numba\core\object_mode_passes.py:152: NumbaWarning: Function "distance_weight_binary_pattern_faster" was compiled in object mode without forceobj=True.

File "LIOT.py", line 81:
def distance_weight_binary_pattern_faster(img):
    <source elided>

    for direction in range(0, 4):
    ^

  state.func_ir.loc))
D:\Anaconda3\envs\pytorch-vessel\lib\site-packages\numba\core\object_mode_passes.py:162: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "LIOT.py", line 81:
def distance_weight_binary_pattern_faster(img):
    <source elided>

    for direction in range(0, 4):
    ^

  state.func_ir.loc))

Process finished with exit code 0

**Comment by TY-Shi** [comment]
Thanks for your attention. This warning is caused by the numba.jit to accelerate. We will release a faster version later.  Most important, this warning does not affect LIOT image generation.  Remember to uncomment these two lines 
“deal_filename = save_path[:-4] + ".tiff"
“tifffile.imsave(deal_filename,Deal_img)” to save LIOT image.
