### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by htx-rest** [TY-Shi/LIOT#5]
可以上传处理后的STARE、CHASEDB1的数据集吗

**Comment by TY-Shi** [comment]
感谢对我们工作的关注！你可以试着用LIOT.py进行任意图像的LIOT变换！

**Comment by TY-Shi** [comment]
记得修改图像路径，把保存图像的lainghang 代码注释去掉！
”deal_filename = save_path[:-4] + ".tiff"“
”tifffile.imsave(deal_filename,Deal_img)“
另外，我们之后也会有可以进行线上训练的LIOT版本，因为手头还有别的工作所以暂时还没有发布，不过相信在1-2个月后很快会发布出来的！

**Comment by htx-rest** [comment]
谢谢，已经解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyi ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TY-Shi/LIOT] 数据集 (Issue #5)





 
记得修改图像路径，把保存图像的lainghang 代码注释去掉！
 ”deal_filename = save_path[:-4] + ".tiff"“
 ”tifffile.imsave(deal_filename,Deal_img)“
 另外，我们之后也会有可以进行线上训练的LIOT版本，因为手头还有别的工作所以暂时还没有发布，不过相信在1-2个月后很快会发布出来的！
