### ISSUE TITLE
Drive训练模型应用在ChaseDB上的精度问题

### ISSUE THREAD

**Issue by icyclv** [TY-Shi/LIOT#6]
您好，请问我将您公开的Drive训练权重用来预测ChaseDB时，最高的F1分数为0.55左右，而不能达到0.7以上，请问在预测时除了liot处理外还需要其他处理吗？

**Comment by TY-Shi** [comment]
请问CHASEDB1数据是经过resize的吗？CHASEDB1数据需要稍微resize下，文中应该有相应的描述，如果有问题可以再讨论。

**Comment by TY-Shi** [comment]
另外，分割的阈值由于是不同数据，不是0.5，而是以一个能达到最佳F1的阈值进行分割，以表现不同方法的一个最好的性能（文中也讲过，所有方法都是公平的比较方式）

**Comment by icyclv** [comment]
> 另外，分割的阈值由于是不同数据，不是0.5，而是以一个能达到最佳F1的阈值进行分割，以表现不同方法的一个最好的性能（文中也讲过，所有方法都是公平的比较方式）

非常感谢！
