### ISSUE TITLE
Questions about the connectivity

### ISSUE THREAD

**Issue by Puzzled-Hui** [TY-Shi/LIOT#7]
This is a wonderful work!!

I have a small question about the connectivity metric used, which i could not find the implementation in your code?

**Comment by TY-Shi** [comment]
Thanks for your attention! This metric is from an open-source code. Thus, we don't put this in our code. You can find this metric code in this implementation link. I think it will help you and we will launch related work in the future so you can pay more attention to it. https://github.com/MIA2I/SkeletalSimilarityMetric

**Comment by Puzzled-Hui** [comment]
> Thanks for your attention! This metric is from an open-source code. Thus, we don't put this in our code. You can find this metric code in this implementation link. I think it will help you and we will launch related work in the future so you can pay more attention to it. https://github.com/MIA2I/SkeletalSimilarityMetric

Thank you for your reply! I will refer to the materials you kindly provided :) Nice work! Congrats to you!
