### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by htx-rest** [TY-Shi/LIOT#8]
您好，在跑CHASDE_DB1实验时效果有点差，请问可以分享一下您在CHASDE_DB1上的训练模型吗？谢谢

**Comment by htx-rest** [comment]
![UYL~(FWBW())4IJHCX _5S8](https://user-images.githubusercontent.com/59019845/186653727-28073f40-ec92-46b8-82c3-2168ebe57acd.png)
在CHASE_DB1数据集上训练出现该问题，并且学习率保持不变，预测的结果全为黑，这个是为什么呢？

**Comment by htx-rest** [comment]
![image](https://user-images.githubusercontent.com/59019845/186654145-157b2c61-b740-4f9a-a32b-2a69546ea214.png)

**Comment by TY-Shi** [comment]
这个问题你可以看看为什么length这个参数是0，因为这个应该是在表示不同的样本数量。这个问题应该是比较好解决的看一下输入的likehoodmap的长度。另外，这个问题是在训练的过程中出现的，其实我也不知道为什么会出现这样为0的情况，你可以更详细的看一下这个bug，我们之前没注意到这个问题，我怀疑是不是数据读取的问题。另外，CHASEDB1的模型因为做了很多组实验，之后如果你们没有解决这个问题，我再去选择一组或多组模型上传。

**Comment by htx-rest** [comment]
谢谢，已解决，是数据读取问题，数据读取时将标签值255读取为1，导致后面处理时将其全部处理为0，不满足循环的条件，未进入循环，导致全局变量的值未更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyi ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 中午12:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TY-Shi/LIOT] 数据集 (Issue #8)





 
这个问题你可以看看为什么length这个参数是0，因为这个应该是在表示不同的样本数量。这个问题应该是比较好解决的看一下输入的likehoodmap的长度。另外，这个问题是在训练的过程中出现的，其实我也不知道为什么会出现这样为0的情况，你可以更详细的看一下这个bug，我们之前没注意到这个问题，我怀疑是不是数据读取的问题。另外，CHASEDB1的模型因为做了很多组实验，之后如果你们没有解决这个问题，我再去选择一组或多组模型上传。
