### ISSUE TITLE
A question about /test/1st_manual/

### ISSUE THREAD

**Issue by Pull-Qutter** [TY-Shi/LIOT#9]
in file prepare_datasets.py， we see
```python
groundTruth_imgs_test = "/mnt/nas/DRIVE/test/1st_manual/"
```

but there is no such file `1st_manual` in test set, it's only shown in trainning set

So what the exactly meaning of `/test/1st_manual/` here?

Thanks

**Comment by TY-Shi** [comment]
It is the ground truth for the test image. You can download the DRIVE dataset. (download dir is in readme) If you like our work, you can give our project a star.

**Comment by Pull-Qutter** [comment]
thx
